---
- hosts: servers
  user: root
  sudo: True
  tasks:
    - name: Install the libselinux-python package
      yum: name=libselinux-python
    - name: Stop Container
      shell: docker stop 798645301fbd 
	#- name: Delete Old Files
	- name: Copy files
      copy: src=/root/.jenkins/jobs/SCALA-SOQ-SOAQXXXX/workspace/target/universal/soaq-1.0-SNAPSHOT.zip dest=/home/soaq
    - name: Unzip files
      unarchive: src=/root/.jenkins/jobs/SCALA-SOQ-SOAQXXXX/workspace/target/universal/soaq-1.0-SNAPSHOT.zip dest=/home/soaq copy=yes
    - name: install docker-py
      pip: name=docker-py
    - name: Install the libselinux-python package
      yum: name=libselinux-python state=installed
    - name: Start Container
      shell: docker start 798645301fbd
    - name: Enter Container
      shell: docker exec -it 798645301fbd /bin/bash 
	- name: Run nohup
      shell: nohup /opt/soaq_latest/bin/soaq -Dhttp.port=1212 -Dlogger.resource=prod-logger.xml -Dconfig.file=trunk.conf &
docker exec -it 798645301fbd /bin/bash "nohup /opt/soaq_latest/bin/soaq -Dhttp.port=1212 -Dlogger.resource=prod-logger.xml -Dconfig.file=trunk.conf &"