---
- hosts: pythonservers
  sudo: true

  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: {{ system_packages }}

  - name: Install required Python packages.
    easy_install: name={{ item }}
    with_items: {{ python_packages }}

  - name: Change permissions.
    shell: chown -R {{ project_name }}:{{ project_name }} {{ project_root }}

  - name: Install nginx configuration file.
    copy: src=files/conf/nginx.conf dest=/etc/nginx/sites-enabled/{{ project_name }}
    notify: restart nginx

  - name: Install init scripts.
    copy: src=files/init/{{ item }}.conf dest=/etc/init/{{ project_name }}_{{ item }}.conf
    with_items: {{ initfiles }}

  - name: Create database.
    shell: {{ project_root }}/env/bin/python {{ project_root }}/code/webapp/manage.py sqlcreate --router=default | sudo -u postgres psql

  handlers:
    - include: handlers.yml

- include: deploy.yml

- hosts: pythonservers
  sudo: true
  tasks:
  - name: Restart services.
    service: name={{ project_name }}_{{ item }} state=restarted
    with_items: {{ initfiles }}